### PR TITLE
update to check_rates_history page

### PR DESCRIPTION
**Pull request by tannerbk**
- Rename to cmos rates history
- Add new starting run range (200k)
- Add an ending run range

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
Happy to merge this as is, but I wonder if it wouldn't be too hard if you could update it to plot things as a function of time instead of run number? I set up the base currents page to do that and it is sometimes helpful to be able to go back and look at the history over the period of a year or more.

**Comment by tannerbk** [comment]
Sure I'll update to something similar for the cmos rates.

**Comment by tannerbk** [comment]
check out the cmos rates on 11/4/0, very strange.

**Comment by tlatorre-uchicago** [comment]
Woah interesting. How did you find that?

One issue I see with the current implementation is that it takes *forever* to load the page if you specify the run range as 100,000 - current run. I'm not entirely sure why that is, it must have something to do with the SQL query. On the current base current and check rates page it takes only a few seconds to load, but if I go to channel 11/4/0 and change the start run to 100,000 it seems to take forever (it's been at least a minute and it hasn't loaded yet).

**Comment by tannerbk** [comment]
Just randomly playing with the page haha. 

I didn't try loading a large run-range -- I'll try and figure out why its so slow today on shift.

**Comment by tannerbk** [comment]
nvm, I think ordering by run should speed the query up a lot.

**Pull request merged**
