### PR TITLE
Add heartbeat to mtca baseline monitor script

### PR DESCRIPTION
**Pull request by tannerbk**

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
Currently the mtca_baseline script is monitored by nagios. Do you think it makes sense to alarm the shifter about this? Since they can't do anything about it except contact the expert I wonder if it makes more sense to figure out a way to propagate the nagios alarm to the daq expert group somehow.

**Comment by tannerbk** [comment]
In that sense its the same as almost all the other heartbeat alarm, right? The shifter pretty much has no course of action except contact an expert.

**Comment by tlatorre-uchicago** [comment]
Yeah I guess it's partly historical. Most of the other servers aren't monitored by nagios since the heartbeat alarms already existed.

One difference I can see is that the baseline monitoring isn't necessary to take quality data whereas the others are. If the mtc/data/log servers go down we pretty much can't take data (well, technically you could with the log server) and so it seems reasonable to add it to the alarms since an expert should be called *immediately* if any of these aren't working.

That seems like a reasonable distinction to me, because in fact there are lots of other programs similar to the baseline monitor that don't have heartbeats:

- cmos script
- base current script
- dispatch script
- manip logger
- digitemp script
- sync monitor

There are then a couple that do have heartbeats that probably don't need to like the noel server.

There is one script that probably should have a heartbeat but as of now is only monitored by nagios and that's the daq_runner script which is necessary to save the detector state.

**Comment by tannerbk** [comment]
OK that makes sense. The use case here was there were several times after the timing rack was turned on that this script didn't come up automatically and we didn't have baseline data for a couple hours or so during physics running. The nagios alerts would accomplish the same goal, so I'd be happy with that.

**Pull request closed without merging**
