### PR TITLE
New deck activity page 

### PR DESCRIPTION
**Pull request by tannerbk**
- Also added a entry to db.py for the test database

### CODE REVIEW

**Comment by tannerbk** [comment]
Deck GUI is now deployed in the DAQ release 1.5.5

**Comment by tlatorre-uchicago** [comment]
Could you delete the test database entry and squash everything into one commit? Would also be cool if you could page back through the results. To see an example of where that's currently done check out the code for the Orca control rooms. Essentially you just need to add an offset parameter to the query which defaults to 0.

**Comment by tannerbk** [comment]
Doh, that squash didn't really work, I'll just create a new clean pull request.

**Comment by tannerbk** [comment]
Closed in favor of #198.

**Pull request closed without merging**
