### PR TITLE
migrate nearline status to psql

### PR DESCRIPTION
**Pull request by tannerbk**
Should wait for associated nearline pull request to be merged.

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
Do you plan to (or have already done) move all the previous runs to the psql database?

**Comment by tannerbk** [comment]
Yah it should be 99% migrated (up to run 108939) and it actually contains some additional information since I've been updating it with the status of jobs run from Penn. I'll finish the migration once we start running the nearline with the psql database.

**Comment by tannerbk** [comment]
Should be ready to go

**Comment by tannerbk** [comment]
This now updates and renames the nearline summary page.

**Comment by tlatorre-uchicago** [comment]
One difference seems to be on the nearline failures page where in the current (redis) version, I see lots of ping crates failures (for example runs 109248, 109247, etc.) but these do not show up as failures in the new page. Is this expected?

**Comment by tannerbk** [comment]
Yah those were reprocessed after I migrated the database over.

**Pull request merged**
