### PR TITLE
Supernova Burst Trigger: updates to Level 2 and addition of Level 3 m…

### PR DESCRIPTION
**Pull request by MRiganSUSX**
…onitoring.

Global
-> changed layout: renamed L2 to Supernova, added Level 3 pages.

L2
-> improvements to visuals to L2 list table 
-> changed layout of run detail page: grouping similar elements in tables, made headers bold

L3
-> made overview page, including list of cuts (loaded from couch), loading variables from redis
-> made burst list table, slightly different variables loaded from couch than L2
-> run detail page: follows the new scheme of L2, some additional plots and details

Other:
-> corresponding functions in .js, burst.py, views.py ...

### CODE REVIEW

**Comment by MRiganSUSX** [comment]
Hi @tlatorre-uchicago, please let me know if this needs any changes. Thanks.

**Comment by tannerbk** [comment]
@MRiganSUSX can you resolve the merge conflicts before I take a look today?

**Comment by MRiganSUSX** [comment]
@tannerbk I don't have permissions I think? (As in I can't even see what the conflicts are...)
github

**Comment by tannerbk** [comment]
You can do it locally. From your master branch create a new branch:
```git checkout -b branch_name```
Then pull down your changes (or just merge the local version):
```git pull origin pull/233/head```
Then you can view the merge conflicts for those files and fix them.

**Pull request closed without merging**
